In [1]:
import sys
import numpy as np

In [2]:
sys.path.append("/home/zanardi/Codes/ML/RONEK/ronek/")
from ronek.argon_plasma.model import Model

In [3]:
path_to_dtb = "/home/zanardi/Codes/ML/RONEK/ronek/examples/CR_Ar/database"
species_order = ("Ar", "Arp", "em")

In [4]:
model = Model(
  species={k: path_to_dtb + "/species/" + k + ".json" for k in species_order},
  kin_dtb=path_to_dtb + "/rates/kin_fit.p"
)

In [5]:
p0, T0, T = 1e3, 5e2, 3e4

In [6]:
w, rho = model.mix.get_init_composition(p0, T0, noise=False)
model.mix.update_composition(w, rho)
model.mix.update_species_thermo(T, T0)
model.mix.update_mixture_thermo()

In [7]:
t = np.geomspace(1e-12,1e-2,499)
t = np.insert(t, 0, 0)

In [8]:
y0 = np.concatenate([w, model.mix.e, model.mix.e_e])
y0, rho

(array([1.00000000e+00, 1.00000000e-25, 1.00000000e-25, 1.00000000e-25,
        1.00000000e-25, 1.00000000e-25, 1.00000000e-25, 1.00000000e-25,
        1.00000000e-25, 1.00000000e-25, 1.00000000e-25, 1.00000000e-25,
        1.00000000e-25, 1.00000000e-25, 1.00000000e-25, 1.00000000e-25,
        1.00000000e-25, 1.00000000e-25, 1.00000000e-25, 1.00000000e-25,
        1.00000000e-25, 1.00000000e-25, 1.00000000e-25, 1.00000000e-25,
        1.00000000e-25, 1.00000000e-25, 1.00000000e-25, 1.00000000e-25,
        1.00000000e-25, 1.00000000e-25, 1.00000000e-25, 1.00000000e-25,
        1.00000000e-25, 1.00000000e-25, 9.36594618e+06, 1.13672536e-15]),
 0.009609280078493638)

In [9]:
model._fun(0.0, y0, rho)

[30000.] [500.]
[30000.] [500.]


array([-7.72551440e+02,  3.35191830e-18,  1.48186344e+02, -6.54861330e-19,
        4.97171489e+02, -5.84958624e-18,  1.51111978e-15, -8.59212337e-16,
       -1.40122195e-15,  1.49718212e-15, -1.04225636e-14,  7.77040875e-15,
        2.97974143e-15, -8.07408343e-16, -2.46568287e-16, -2.26173848e-15,
        6.12566691e-01,  3.64732821e-16,  7.90486162e-16,  3.66868715e-16,
        7.52878770e-16,  1.06610702e-15,  1.83754455e+01,  9.69184902e-15,
        4.96387031e+01,  4.96986027e-15, -9.43961950e-15,  4.87193721e-13,
       -4.81079932e-13,  8.88906276e+00,  3.81763486e+01,  1.15013226e+01,
        3.09202439e-18,  1.57942354e-04,  0.00000000e+00,  4.67350779e-10])

In [10]:
model.solve(t, y0, rho)

[30000.] [500.]
[30000.] [500.]
[29999.99999927] [3.16571177e-05]
[29999.99999927] [300.]
[29999.99999927] [3.40964659e-05]
[29999.99999927] [300.]
[29999.99999854] [1.82679185e-05]
[29999.99999854] [300.]
[29999.99999854] [1.94876237e-05]
[29999.99999854] [300.]
[29999.9999868] [2.39525371e-05]
[29999.9999868] [300.]
[29999.9999868] [2.39558817e-05]
[29999.9999868] [300.]
[29999.99997507] [4.27009543e-05]
[29999.99997507] [300.]
[29999.99997507] [4.2704279e-05]
[29999.99997507] [300.]
[29999.99996333] [6.20227949e-05]
[29999.99996333] [300.]
[29999.99996333] [6.20250454e-05]
[29999.99996333] [300.]
[29999.99995283] [7.94498521e-05]
[29999.99995283] [300.]
[29999.99995283] [7.94511742e-05]
[29999.99995283] [300.]
[29999.99994233] [9.69348752e-05]
[29999.99994233] [300.]
[29999.99994233] [9.69358931e-05]
[29999.99994233] [300.]
[29999.99993183] [0.00011445]
[29999.99993183] [300.]
[29999.99993183] [0.00011445]
[29999.99993183] [300.]
[29999.9999072] [0.00015561]
[29999.9999072] [300.]
[

array([[1.00000000e+00, 9.99999999e-01, 9.99999999e-01, ...,
        8.60377738e-01, 8.60374811e-01, 8.60372701e-01],
       [1.00000000e-25, 3.91393401e-16, 4.29281287e-16, ...,
        3.17305323e-05, 3.17291621e-05, 3.17282103e-05],
       [9.99644539e-26, 1.48185090e-10, 1.55197477e-10, ...,
        1.76275265e-05, 1.76267602e-05, 1.76262280e-05],
       ...,
       [1.00000000e-25, 1.57947036e-16, 1.65421673e-16, ...,
        1.91532518e-06, 1.91536547e-06, 1.91539451e-06],
       [9.36594618e+06, 9.36594618e+06, 9.36594618e+06, ...,
        9.36594618e+06, 9.36594618e+06, 9.36594618e+06],
       [1.13672536e-15, 4.39506014e-13, 4.81984898e-13, ...,
        4.93807429e+05, 4.93816074e+05, 4.93822354e+05]])